export const SET_ACCESS_TOKEN = "SET_ACCESS_TOKEN";
export const SET_USER_INFO = "SET_USER_INFO";
export const CLEAR_USER = "CLEAR_USER";

export const SET_POST_PICTURES = "SET_POST_PICTURES";
export const SET_BRAND_DETAILS = "SET_BRAND_DETAILS";
export const SET_POST_CAPTION = "SET_POST_CAPTION";
export const SET_PRODUCT_TAGS = "SET_PRODUCT_TAGS";
export const CLEAR_POST = "CLEAR_POST";